version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./:/opt/dagster/app
    ports:
      - "3000:3000"
    environment:
      # DAGSTER_HOME already set in Dockerfile; no DB env vars needed.
      PYTHONUNBUFFERED: "1"
